module.exports = {
	actionConst: {
		SET_USER_CURRENT_INPUT: 'SET_USER_CURRENT_INPUT',
		SUBMIT_USER_INPUT: 'SUBMIT_USER_INPUT',
		NEW_LOG_ENTRY: 'NEW_LOG_ENTRY',
		SEND_COMMAND: 'SEND_COMMAND',
		INVALID_COMMAND: 'INVALID_COMMAND',
		NEW_USER: 'NEW_USER',
	},
	commandNames: {
		EAT: 'eat',
		SAY: 'say',
	}
}
