module.exports = {
	actionConst: {
		SET_USER_CURRENT_INPUT: 'SET_USER_CURRENT_INPUT',
		SUBMIT_USER_INPUT: 'SUBMIT_USER_INPUT',
		NEW_LOG_ENTRY: 'NEW_LOG_ENTRY',
		SEND_COMMAND: 'SEND_COMMAND',
		INVALID_COMMAND: 'INVALID_COMMAND',
		NEW_USER: 'NEW_USER',
		UPDATE_LINK: 'UPDATE_LINK',
		SUBMIT_LINK: 'SUBMIT_LINK',
		MUSIC_DOWNLOAD: 'MUSIC_DOWNLOAD',
		MUSIC_FAIL: 'MUSIC_FAIL',
	},
	commandNames: {
		EAT: 'eat',
		SAY: 'say',
	}
}
